#!/usr/bin/env python3
"""
Test Script for Resynth Persona Dataset Generation
Mocks the LLM to verify pipeline logic.
"""

import os
import random
import json
import re
import pandas as pd
import nltk
from nltk.corpus import names
from datasets import load_dataset

# ═══════════════════════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════════════════════

HF_SOURCE_DATASET = "G-reen/Resynth-Base-Scored" 
DELUSIONAL_THRESHOLD = 0.6
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROMPTS_DIR = os.path.join(SCRIPT_DIR, "prompts", "2-persona")
INIT_PROMPT_PATH = os.path.join(PROMPTS_DIR, "init.txt")
TRAITS_PATH = os.path.join(PROMPTS_DIR, "traits.txt")
EVOLVE_DIR = os.path.join(PROMPTS_DIR, "evolve")

# ═══════════════════════════════════════════════════════════════════════════════
# Mock LLM
# ═══════════════════════════════════════════════════════════════════════════════

class MockOutput:
    def __init__(self, text):
        self.text = text
        
class MockCompletion:
    def __init__(self, text):
        self.outputs = [MockOutput(text)]

class MockLLM:
    def generate(self, prompts, sampling_params, use_tqdm=False):
        results = []
        for p in prompts:
            # We just return a dummy response
            output_text = "This is a test personality profile generated by the mock LLM.\n### Profile:\nNAME: Test User\nTRAITS: Test, Mock\nBIO: This is a mock bio."
            results.append(MockCompletion(output_text))
        return results
        
    def get_tokenizer(self):
        return MockTokenizer()

class MockTokenizer:
    def apply_chat_template(self, conversation, tokenize=False, add_generation_prompt=True):
        text = ""
        for msg in conversation:
            text += f"[{msg['role'].upper()}]: {msg['content']}\n"
        return text

# ═══════════════════════════════════════════════════════════════════════════════
# Utils
# ═══════════════════════════════════════════════════════════════════════════════

def setup_names():
    print("Setting up name generation...")
    try:
        nltk.download('names', quiet=True)
        male_first_names = list(set(names.words('male.txt')))
        female_first_names = list(set(names.words('female.txt')))
    except LookupError:
        print("NLTK data missing, downloading...")
        nltk.download('names')
        male_first_names = list(set(names.words('male.txt')))
        female_first_names = list(set(names.words('female.txt')))
    
    url = "https://raw.githubusercontent.com/fivethirtyeight/data/master/most-common-name/surnames.csv"
    try:
        df = pd.read_csv(url)
        exhaustive_last_names = df['name'].dropna().str.title().tolist()
    except Exception:
        exhaustive_last_names = ["Smith", "Johnson", "Williams"]

    return male_first_names, female_first_names, exhaustive_last_names

def generate_exhaustive_name(male_first, female_first, last_names):
    if random.random() < 0.5:
        first = random.choice(male_first)
    else:
        first = random.choice(female_first)
    last = random.choice(last_names)
    return f"{first} {last}"

def load_traits():
    if not os.path.exists(TRAITS_PATH):
        return ["average", "normal"]
    with open(TRAITS_PATH, 'r') as f:
        content = f.read().strip()
    return [t.strip() for t in re.split(r'[,\n]+', content) if t.strip()]

def load_prompts():
    if not os.path.exists(INIT_PROMPT_PATH):
        return "Imagine a user {{name}} with traits {{traits}}. Question: {{question}}", ["Evolve this personality."]
        
    with open(INIT_PROMPT_PATH, 'r') as f:
        init_template = f.read().strip()
    
    evolve_templates = []
    if os.path.exists(EVOLVE_DIR):
        for fname in os.listdir(EVOLVE_DIR):
            if fname.endswith(".txt"):
                with open(os.path.join(EVOLVE_DIR, fname), 'r') as f:
                    evolve_templates.append(f.read().strip())
    
    if not evolve_templates:
        evolve_templates = ["Please add more detail to this personality."]
        
    return init_template, evolve_templates

# ═══════════════════════════════════════════════════════════════════════════════
# Main Logic
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    # 1. Setup Resources
    male_first, female_first, last_names = setup_names()
    all_traits = load_traits()
    init_template, evolve_templates = load_prompts()
    
    # 2. Load Dataset
    print(f"Loading dataset: {HF_SOURCE_DATASET} (streaming mode)")
    ds = load_dataset(HF_SOURCE_DATASET, split="train", streaming=True)
    
    processing_queue = []
    
    count = 0
    # Iterate through the streaming dataset
    for row in ds:
        # Check standard keys based on inspection
        # Keys found: ['final_prompt', 'conversation', 'delusional_score', ...]
        user_prompt = row.get("final_prompt") or row.get("prompt") or row.get("original_prompt")
        
        if not user_prompt:
            continue
            
        # Filter by delusion score if present
        d_score = row.get("delusional_score", 0)
        if d_score is not None and d_score > DELUSIONAL_THRESHOLD:
            continue

        # Generate identity
        full_name = generate_exhaustive_name(male_first, female_first, last_names)
        
        # Pick traits
        num_traits = random.randint(1, 3)
        chosen_traits_list = random.sample(all_traits, k=min(num_traits, len(all_traits)))
        traits_str = ", ".join(chosen_traits_list)
        
        # Fill template
        init_content = init_template.replace("{{name}}", full_name) \
                                    .replace("{{traits}}", traits_str) \
                                    .replace("{{question}}", user_prompt)
        
        evolve_steps = 1 # Force 1 evolve for test
        
        processing_queue.append({
            "original_prompt": user_prompt,
            "tags": row.get("tags", []),
            "conversation": [{"role": "user", "content": init_content}],
            "evolve_target": evolve_steps,
            "evolve_count": 0,
            "completed": False,
            "last_response": None
        })
        
        count += 1
        if count >= 3: # Limit to 3 items for testing
            break
            
    print(f"Prepared {len(processing_queue)} items for generation.")

    if not processing_queue:
        print("Error: No items prepared. Check dataset keys or connection.")
        return

    # 3. Initialize Mock LLM
    print("Initializing Mock LLM...")
    llm = MockLLM()
    tokenizer = llm.get_tokenizer()

    # 4. Processing Loop
    active_batch = processing_queue
    completed_items = []
    
    while active_batch:
        print(f"\n--- Batch Pass (Active: {len(active_batch)}) ---")
        
        # Prepare prompts
        prompts = []
        for item in active_batch:
            prompt_text = tokenizer.apply_chat_template(item["conversation"], tokenize=False, add_generation_prompt=True)
            prompts.append(prompt_text)
            
        # Generate
        outputs = llm.generate(prompts, None)
        
        next_active_batch = []
        
        for i, output in enumerate(outputs):
            item = active_batch[i]
            generated_text = output.outputs[0].text.strip()
            
            # Append assistant response
            item["conversation"].append({"role": "assistant", "content": generated_text})
            item["last_response"] = generated_text
            
            # Print intermediate interaction
            print(f"\n[Item {i}] Interaction Step {item['evolve_count']}:")
            print(f"--- Full User Prompt ---")
            print(item['conversation'][-2]['content'])
            print(f"--- End User Prompt ---")
            
            # Check evolve
            if item["evolve_count"] < item["evolve_target"]:
                evolve_prompt_text = random.choice(evolve_templates)
                suffixed_prompt = evolve_prompt_text + "\nBegin your output with ### Profile:, do not output anything after you finish writing the character personality profile."
                
                item["conversation"].append({"role": "user", "content": suffixed_prompt})
                item["evolve_count"] += 1
                next_active_batch.append(item)
            else:
                item["completed"] = True
                completed_items.append(item)
        
        active_batch = next_active_batch

    print("\n\n=== Final Output Verify ===")
    for item in completed_items:
        text = item["last_response"]
        if "### Profile" in text:
            parts = text.split("### Profile")
            personality = parts[-1]
        else:
            personality = text
            
        print(f"Original Prompt: {item['original_prompt'][:50]}...")
        print(f"Final Personality extracted: {personality[:50]}...")
        print("-" * 40)

if __name__ == "__main__":
    main()
